feat: add tunning-es-storage
fossil-engineering/fossil-engineering.github.io pull request #61
Opened 2022-07-29 16:24 UTC by hungtran150

2022-07-29 16:31 UTC, duyet commented
@duyetbot /check typo

2022-07-29 17:01 UTC, hungtran150 commented
> 

Resolved

2022-08-03 07:59 UTC, HieuNT93 commented on data/blog/2022-07-29-tuning-es-storage.md
> +Norms lưu trữ các yếu tố chuẩn hóa khác nhau giúp ích cho việc tại thời điểm truy vấn có thể tính điểm dữ liệu khi truy vấn. Mặc dù hữu ích cho việc tính điểm, đáp ứng nhu cầu cho việc tìm kiếm gần đ
Please check the spelling error. `nhu cấu`

2022-08-03 08:00 UTC, HieuNT93 commented on data/blog/2022-07-29-tuning-es-storage.md
> +Thậm trí nếu bạn không cần tổng hợp, sắp xếp hay thay đổi giá trị của một trường dữ liệu chúng ta có hoàn toàn có thể tắt doc values để tối ưu bộ nhớ.
`Thậm chí` not `Thậm trí`

2022-08-03 08:05 UTC, HieuNT93 reviewed
NACK!

2022-08-03 08:21 UTC, duyet commented on data/blog/2022-07-29-tuning-es-storage.md
> +Elasticsearch không còn quá xa lạ đặc biệt là đối với các Data Engineer trong bài này mình sẽ không nói đến việc Elasticsearch làm việc như thế nào mà mình sẽ đề cập đến một vấn đề khi cài đặt Elasti
Có 2 cách:
- Sử dụng `es` -> `Elasticsearch` cho toàn văn.
- hoặc sử dụng từ viết tắt `ES`, ghi chú viết tắt `Elasticsearch (ES)` trước đó, sau đó sử dụng `ES` từ đó trở về sau.

2022-08-03 11:14 UTC, duyet requested changes

2022-08-03 11:14 UTC, duyet commented on data/blog/2022-07-29-tuning-es-storage.md
> +Doc values là một kiểu dữ liệu trên đĩa (the on-disk data structure). Phần lớn các fields sẽ được mặc định lập chỉ mục (indexed) giúp chúng có thể tìm kiếm (searchable). [Numeric types](https://www.e
truy xuất **bị** đánh đổi

2022-08-03 11:14 UTC, duyet commented on data/blog/2022-07-29-tuning-es-storage.md
> +Doc values là một kiểu dữ liệu trên đĩa (the on-disk data structure). Phần lớn các fields sẽ được mặc định lập chỉ mục (indexed) giúp chúng có thể tìm kiếm (searchable). [Numeric types](https://www.e
Better: Ở Fossil, ngay cả khi tốc độ truy xuất bị đánh đổi, cơ bản nó vẫn nhanh hơn rất nhiều so với Athena.

Bỏ **thậm chí**: lỗi lặp từ với câu bên dưới

2022-08-03 11:14 UTC, duyet commented on data/blog/2022-07-29-tuning-es-storage.md
> +Và chúng ta xem bộ nhớ của chúng ta đã giảm như thế nào:
`chúng ta` lỗi lặp từ

2022-08-03 11:14 UTC, duyet commented on data/blog/2022-07-29-tuning-es-storage.md
> +```
Nên thêm mục **References**

2022-08-08 08:08 UTC, hungtran150 commented
Ready to Deploy @duyet @HieuNT93

2022-08-09 15:59 UTC, merged